CREATE GENERATOR documentoTipoID;
CREATE GENERATOR localidadID;
CREATE GENERATOR reparticionID;
CREATE GENERATOR bancoID;
CREATE GENERATOR afiliadoEstadoID;
CREATE GENERATOR ContactoID;


SET GENERATOR documentoTipoID TO 0;
SET GENERATOR localidadID TO 0;
SET GENERATOR reparticionID TO 0;
SET GENERATOR bancoID TO 0;
SET GENERATOR afiliadoEstadoID TO 0;
SET GENERATOR ContactoID TO 0;

