CREATE GENERATOR documentoTipoID;
CREATE GENERATOR localidadID;
CREATE GENERATOR reparticionID;
CREATE GENERATOR bancoID;
CREATE GENERATOR afiliadoEstadoID;



SET GENERATOR documentoTipoID TO 0;
SET GENERATOR localidadID TO 0;
SET GENERATOR reparticionID TO 0;
SET GENERATOR bancoID TO 0;
SET GENERATOR afiliadoEstadoID TO 0;